service:
  name: serverless-boilerplate

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-admin

functions:
  query:
    handler: handler.query
    events:
      - http:
          method: post
          path: /
